### ISSUE TITLE
Library License

### ISSUE THREAD

**Issue by chrisritter** [2kool2/GIF-pause#1]
Hey Mike @2kool2,

This looks pretty ideal for web page gifs.

What is the license on this little script?

- Chris

**Comment by 2kool2** [comment]
Free to use & abuse as you wish Chris.
A commented reference to where it came from would be nice, but far from 
essential.

Staring it on Github would help too, as I'm currently looking for a new 
employer.
Shameless self promotion here I come.

Thanks for asking.


Mike
